Capstone Project Microverse module 1
lucas-crodrigues/capstone-module-1 pull request #1
Opened 2022-04-20 21:59 UTC by lucas-crodrigues

This is the first capstone project in my Microverse journey.

For this project, we were required to follow the template provided [here](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), but fill it with the content of our choosing.

My content is fictional but based on [this seminar](https://institutoayrtonsenna.org.br/pt-br/seminario-internacional-motivacao.html) by [Instituto Ayrton Senna](https://institutoayrtonsenna.org.br/en.html).

Here is the link to the [Loom video](https://www.loom.com/share/4cbc3ed299894b859ee2a835471e003b) presenting the code.

2022-04-20 22:58 UTC, lucas-crodrigues commented
As you can see I'm getting those "Error: Process completed with exit code 1." on my linters, apart from that they're all passing.

2022-04-21 01:08 UTC, Hamzaoutdoors requested changes
Hey @lucas-crodrigues , I am **Hamza** your reviewer for this PR 😸 

_Good job so far! I enjoyed surfing your fancy website_
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://media.giphy.com/media/42AFvimyQTNQW44PNG/giphy.gif)

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README

## Required Changes ♻️

🔴  - [REQUIRED] You are asked in this project to record a **5min** that contains a demo of your project, showing the pages in different screen sizes and some highlights about a piece of the code that you find interesting and proud of, Kindly record a video and give the link in your README and inside you Pull Request description.

🔴 - [REQUIRED] As required in this capstone project, your project should've deployed using the `GitHub Pages` and add the link in your Readme file, Kindly add a deployment to this amazing web page and let the world explore it 😄 

_See the inline comments below for more required changes 😃_  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
**N.A**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @hamzaoutdoors in your question so I can receive the notification ^_^

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 01:08 UTC, Hamzaoutdoors commented on scripts.js
> +  const showMore = document.querySelector('.showMore');
- [OPTIONAL] Great job implementing the `show more` functionality in the speaker's section, I am recommending you add the `show less` button that will decreament the speaker's cards ^_^

![design](https://user-images.githubusercontent.com/80895497/164351536-d97730db-59d3-4b1c-a234-e51bac1c3283.PNG)

2022-04-21 17:27 UTC, danmainah approved these changes
Hi @lucas-crodrigues , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 17:27 UTC, danmainah commented on scripts.js
> +function loadSpeakers() { // eslint-disable-line no-unused-vars
- [ ] [OPTIONAL] Kindly try your best to avoid disabling linters in your code, its not good practice to disable linters.

2022-04-21 19:23 UTC, merged